---
# check for things to install
# these are files that may exist in the provision-files directory
# but are externally provided rather than checked in as they may
# change per user or per environment
# boolean variables are set to facilitate configuration below
- name: "check for AnypointStudio.tar.gz"
  command: test -f /vagrant/provision-files/AnypointStudio.tar.gz
  register: hasAS
  ignore_errors: True

- name: "check for AnypointStudio.desktop file"
  command: test -f /vagrant/provision-files/AnypointStudio.desktop
  register: hasASDesktop
  ignore_errors: True

- name: "check for settings.xml"
  command: test -f /vagrant/provision-files/settings.xml
  register: hasSettingsXml
  ignore_errors: True

# configure necessary directories
- name: "fix permissions on .m2 folder"
  file:
    path: /home/vagrant/.m2
    owner: vagrant
    group: vagrant
    state: directory
- name: "make tools directory"
  file:
    path: /home/vagrant/Tools
    owner: vagrant
    group: vagrant
    state: directory
  when: hasAS is succeeded
- name: "make applications directory"
  file:
    path: /home/vagrant/.local/share/applications
    owner: vagrant
    group: vagrant
    state: directory
- name: "install anypoint studio"
  unarchive:
    src: /vagrant/provision-files/AnypointStudio.tar.gz
    dest: /home/vagrant/Tools
    owner: vagrant
    group: vagrant
  when: hasAS is succeeded
- name: "copy AnypointStudio desktop file"
  copy:
    src: /vagrant/provision-files/AnypointStudio.desktop
    dest: /home/vagrant/.local/share/applications/AnypointStudio.desktop
    mode: u+rwx
    owner: vagrant
    group: vagrant
  when: hasASDesktop is succeeded
- name: "copy settings.xml file"
  copy:
    src: /vagrant/provision-files/settings.xml
    dest: /home/vagrant/.m2/settings.xml
    mode: u+rw
    owner: vagrant
    group: vagrant
  when: hasSettingsXml is succeeded
