---
- hosts: localhost
  vars:
    elasticsearch: yes
    kibana: yes
    
  roles:
    - { role: pacman-common     }
    - { role: pacman-virtualbox }
    - { role: pacman-xconfig    }
    - { role: aur-packages      }
    - { role: pacman-devtools   }
    - { role: pacman-services   }
    - { role: pacman-shells     }
    - { role: pacman-utils      }
    - { role: pacman-web        }
    - { role: service-config    }
    - { role: user-config       }
