---
- hosts: localhost
  # these have to be passed on the command line
  # --extra-vars "elasticsearch=yes kibana=yes"
  # defaults are no, so not passing them will mean they don't get installed
  vars_prompt:
    - name: "installElasticsearch"
      prompt: "install elasticsearch [yes|no]"
      default: "no"
      private: no
    - name: "installKibana"
      prompt: "install kibana for elasticsearch [yes|no]"
      default: "no"
      private: no
    - name: "installRabbitMQ"
      prompt: "install RabbitMQ"
      default: "no"
      private: no
      
  roles:
    - { role: pacman-common     }
    - { role: pacman-virtualbox }
    - { role: pacman-xconfig    }
    - { role: aur-packages      }
    - { role: pacman-devtools   }
    - { role: pacman-services   }
    - { role: pacman-shells     }
    - { role: pacman-utils      }
    - { role: pacman-web        }
    - { role: service-config    }
    - { role: user-config       }
