---
- hosts: localhost
  vars:
    elasticsearch: yes
    kibana: yes
    
  roles:
    - { role: pacman-common     }
    - { role: pacman-virtualbox }
    - { role: pacman-xconfig    }
    - { role: aur-packages      }
    - { role: pacman-devtools   }
    - { role: pacman-services   }
    - { role: pacman-shells     }
    - { role: pacman-utils      }
    - { role: pacman-web        }
    - { role: service-config    }
    - { role: user-config       }

#    - name: "update all packages first"
#      pacman:
#        update_cache: yes
#        upgrade: yes
#    - name: "remove virtualbox-guest-utils-nox"
#      pacman:
#        name: virtualbox-guest-utils-nox
#        state: absent
#    - name: "install xfce4"
#      pacman:
#        name: xfce4
#        state: latest
#    - name: "install xfce4-goodies"
#      pacman:
#        name: xfce4-goodies
#        state: latest
#    - name: "install xorg"
#      pacman:
#        name: xorg
#        state: latest
#    - name: "install xorg-apps"
#      pacman:
#        name: xorg-apps
#        state: latest
#    - name: "install xorg-fonts"
#      pacman:
#        name: xorg-fonts
#        state: latest
#    - name: "install cantarell-fonts"
#      pacman:
#        name: cantarell-fonts
#        state: latest
#    - name: "install xorg-fonts-alias"
#      pacman:
#        name: xorg-fonts-alias
#        state: latest
#    - name: "install xorg-fonts-misc"
#      pacman:
#        name: xorg-fonts-misc
#        state: latest
#    - name: "install xorg-mkfontscale"
#      pacman:
#        name: xorg-mkfontscale
#        state: latest
#    - name: "install xorg-mkfontdir"
#      pacman:
#        name: xorg-mkfontdir
#        state: latest
#    - name: "install lightdm"
#      pacman:
#        name: lightdm
#        state: latest
#    - name: "install lightdm-gtk-greeter"
#      pacman:
#        name: lightdm-gtk-greeter
#        state: latest
#    - name: "install emacs"
#      pacman:
#        name: emacs
#        state: latest
#    - name: "install intellij-idea-community-edition"
#      pacman:
#        name: intellij-idea-community-edition
#        state: latest
#    - name: "install networkmanager"
#      pacman:
#        name: networkmanager
#        state: latest
#    - name: "install network-manager-applet"
#      pacman:
#        name: network-manager-applet
#        state: latest
#    - name: "install firefox"
#      pacman:
#        name: firefox
#        state: latest
#    - name: "install maven"
#      pacman:
#        name: maven
#        state: latest
#    - name: "install virtualbox-guest-utils"
#      pacman:
#        name: virtualbox-guest-utils
#        state: latest
#    - name: "install virtualbox-guest-iso"
#      pacman:
#        name: virtualbox-guest-iso
#        state: latest
#    - name: "install zip"
#      pacman:
#        name: zip
#        state: latest
#    - name: "install unzip"
#      pacman:
#        name: unzip
#        state: latest
#    - name: "install gvim"
#      pacman:
#        name: gvim
#        state: latest
#    - name: "install perl"
#      pacman:
#        name: perl
#        state: latest
#    - name: "install ack"
#      pacman:
#        name: ack
#        state: latest
#    - name: "install keepass"
#      pacman:
#        name: keepass
#        state: latest
#    - name: "install meld"
#      pacman:
#        name: meld
#        state: latest
#    - name: "install elasitcsearch"
#      pacman:
#        name: elasticsearch
#        state: latest
#    - name: "install zsh"
#      pacman:
#        name: zsh
#        state: latest
#    - name: "install grml zsh configuration"
#      pacman:
#        name: grml-zsh-config
#        state: latest

#    - name: "add autologin group"
#      group:
#        name: autologin
#        system: yes
#        state: present
#    - name: "add autologin group to vagrant"
#      user:
#        name: vagrant
#        append: yes
#        groups: autologin
#    - name: "set zsh as login shell"
#      user:
#        name: vagrant
#        shell: /bin/zsh
#    - name: "configure lightdm to enable autologin for vagrant user"
#      replace:
#        dest: /etc/lightdm/lightdm.conf
#        regexp: '^#autologin-user='
#        replace: 'autologin-user=vagrant'
#    - name: "configure lightdm autologin timeout"
#      replace:
#        dest: /etc/lightdm/lightdm.conf
#        regexp: '^#autologin-user-timeout=0'
#        replace: 'autologin-user-timeout=0'
#    - name: "enable lightdm"
#      systemd:
#        name: lightdm
#        enabled: yes
#    - name: "enable network manager"
#      systemd:
#        name: NetworkManager.service
#        enabled: yes
#    - name: "enable elasticsearch"
#      systemd:
#        name: elasticsearch.service
#        enabled: yes
#    - name: "enable kibana for elasticsearch"
#      systemd:
#        name: kibana.service
#        enabled: yes

#    - name: "create tools directory"
#      file:
#        path: /home/vagrant/Tools
#        owner: vagrant
#        group: vagrant
#        state: directory
#    - name: "install anypoint studio"
#      unarchive:
#        src: /vagrant/provision-files/AnypointStudio.tar.gz
#        dest: /home/vagrant/Tools
#        owner: vagrant
#        group: vagrant
#
#    - name: "create Pictures directory"
#      file:
#        path: /home/vagrant/Pictures
#        owner: vagrant
#        group: vagrant
#        state: directory
#    - name: "unzip some decent backgrounds"
#      unarchive:
#        src: /vagrant/provision-files/wallpapers.zip
#        dest: /home/vagrant/Pictures
#
#    - name: "make autostart directory"
#      file:
#        path: /home/vagrant/.config/autostart
#        owner: vagrant
#        group: vagrant
#        state: directory
#    - name: "make applications directory"
#      file:
#        path: /home/vagrant/.local/share/applications
#        owner: vagrant
#        group: vagrant
#        state: directory
#
#    - name: "copy autostart swap caps file"
#      copy:
#        src: /vagrant/provision-files/SwapCaps.desktop
#        dest: /home/vagrant/.config/autostart/SwapCaps.desktop
#        mode: u+rwx
#        owner: vagrant
#        group: vagrant
#    - name: "copy AnypointStudio desktop file"
#      copy:
#        src: /vagrant/provision-files/AnypointStudio.desktop
#        dest: /home/vagrant/.local/share/applications/AnypointStudio.desktop
#        mode: u+rwx
#        owner: vagrant
#        group: vagrant

#    - name: "make .emacs.d directory"
#      file:
#        path: /home/vagrant/.emacs.d
#        owner: vagrant
#        group: vagrant
#        state: directory
#    - name: "checkout emacs dot files"
#      git:
#        clone: yes
#        dest: /home/vagrant/dotfiles.emacs
#        repo: https://bitbucket.org/jeffbowman/dotfiles.git
#    - name: "copy emacs init.el to .emacs.d/"
#      copy:
#        src: /home/vagrant/dotfiles.emacs/init.el
#        dest: /home/vagrant/.emacs.d/init.el
#        owner: vagrant
#        group: vagrant

#    - name: "set default java"
#      shell: archlinux-java set java-8-jdk
