---
- name: "install OpenJDK 8 - needed for Mule development"
  pacman:
    name: jdk8-openjdk
    state: latest

- name: "install Javadoc for OpenJDK 8"
  pacman:
    name: openjdk8-doc
    state: latest

- name: "install sources for OpenJDK 8"
  pacman:
    name: openjdk8-src
    state: latest
    
- name: "set default java"
  shell: archlinux-java set java-8-openjdk
