---
- name: "checkout emacs dot files"
  git:
    clone: yes
    dest: /home/vagrant/dotfiles
    repo: https://bitbucket.org/jeffbowman/dotfiles.git
  become: yes
  become_user: vagrant

- name: "symlink dotfiles/emacs to ~/.emacs.d"
  file:
    src: /home/vagrant/dotfiles/emacs
    dest: /home/vagrant/.emacs.d
    owner: vagrant
    group: vagrant
    state: link
  become: yes
  become_user: vagrant
